sudo: false

language: python

services:
  - postgresql

install:
  - pip install coverage tox-travis flake8 psycopg2

before_script:
  - psql template1 -c 'create extension hstore;'

script:
  - coverage erase
  - tox
  - flake8 django_admin_hstore_widget/

after_success:
  - coverage combine --append
  - coverage report -m
  - pip install codecov
  - codecov

env:
  - DJANGO=1.11
  - DJANGO=2.0

matrix:
  fast_finish: true
  include:
    # PYTHON 3.7
    - { python: "3.7", env: DJANGO=3.0 }
    - { python: "3.7", env: DJANGO=2.2 }
    - { python: "3.7", env: DJANGO=2.1 }
    - { python: "3.7", env: DJANGO=2.0 }
    # PYTHON 3.6
    - { python: "3.6", env: DJANGO=3.0 }
    - { python: "3.6", env: DJANGO=2.2 }
    - { python: "3.6", env: DJANGO=2.1 }
    - { python: "3.6", env: DJANGO=2.0 }
    - { python: "3.6", env: DJANGO=1.11 }

  exclude:
    - { env: DJANGO=2.0 }
    - { env: DJANGO=1.11 }
