sudo: false

language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

services:
  - postgresql

install:
  - pip install coverage detox tox-travis flake8 psycopg2

before_script:
  - psql template1 -c 'create extension hstore;'

script:
  - coverage erase
  - detox
  - flake8 django_admin_hstore_widget/

after_success:
  - coverage combine --append
  - coverage report -m
  - pip install codecov
  - codecov
