sudo: false

language: python

services:
  - postgresql

install:
  - pip install coverage detox tox-travis flake8 psycopg2

before_script:
  - psql template1 -c 'create extension hstore;'

script:
  - coverage erase
  - detox
  - flake8 django_admin_hstore_widget/

after_success:
  - coverage combine --append
  - coverage report -m
  - pip install codecov
  - codecov

env:
  - DJANGO=1.11
  - DJANGO=2.0

matrix:
  fast_finish: true
  include:
    - { python: "3.6", env: DJANGO=2.0 }
    - { python: "3.6", env: DJANGO=1.11 }
    - { python: "3.5", env: DJANGO=2.0 }
    - { python: "3.5", env: DJANGO=1.11 }
    - { python: "3.4", env: DJANGO=2.0 }
    - { python: "3.4", env: DJANGO=1.11 }
    - { python: "2.7", env: DJANGO=1.11}

  exclude:
    - { python: "2.7", env: DJANGO=2.0 }
    - { env: DJANGO=2.0 }
    - { env: DJANGO=1.11 }
